
services:
  backend:
    build: .
    # image: odehmarkable/employee-profile-api
    # container_name: employee-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production  
    # depends_on ensures that the backend service starts after the postgres service is healthy
    # depends_on value should be same as container_name
    # Note: depends_on does not wait for the service to be "ready", it only waits for it to start. For a more robust solution, consider using a healthcheck in the postgres service and configuring the backend to wait for the database to be ready before starting.
    depends_on:
      - postgres
    restart: always

  # Config name should be same as DB_HOST in .env file
  postgres:
    image: postgres:15
    # container_name: employee-postgres
    environment:
      POSTGRES_USER: odz_admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: employee_profile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  nginx:  
    image: nginx:latest  
    ports:  
      - "80:80"  
      - "443:443"  
    volumes:  
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./certbot/www:/var/www/certbot  
      - ./certbot/conf:/etc/letsencrypt  
    depends_on:  
      - backend   

volumes:
  pgdata: