upstream backend_cluster {
    server backend:3000;
}

# HTTP (REQUIRED FOR CERTBOT)
server {
    listen 80;
    server_name odzfishdeliveryapp.myftp.biz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name odzfishdeliveryapp.myftp.biz;

    ssl_certificate /etc/letsencrypt/live/odzfishdeliveryapp.myftp.biz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/odzfishdeliveryapp.myftp.biz/privkey.pem;

    location / {
        proxy_pass http://backend_cluster;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }


    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self'; connect-src 'self' http: https:;" always;


}