name: Backend CI

on:
  push:
    branches: [main]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    # --------------------------
    # SERVICES
    # --------------------------
    services:
      # PostgreSQL service for testing
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odz_admin
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: employee_profile
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odz_admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    # --------------------------
    # ENVIRONMENT VARIABLES
    # --------------------------

    # Set environment variables for the application
    env:
      DB_HOST: localhost
      DB_USER: odz_admin
      DB_PASS: 1234
      DB_NAME: employee_profile
      DB_PORT: 5432
      JWT_SECRET: 1234
      JWT_EXPIRES_IN: 1d

    # --------------------------
    # STEPS
    # --------------------------
    steps:
      # --------------------------
      # CHECKOUT CODE
      # --------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # --------------------------
      # SETUP NODE AND INSTALL DEPENDENCIES
      # --------------------------
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # --------------------------
      # INSTALL DEPENDENCIES AND RUN TESTS
      # --------------------------
      - name: Install dependencies
        run: npm install

      - name: Run Sequelize migrations
        run: npx sequelize-cli db:migrate

      - name: Run tests
        run: npm test

      # --------------------------
      # BUILD DOCKER IMAGE
      # --------------------------

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/employee-profile-api .

      # --------------------------
      # LOGIN TO DOCKERHUB
      # --------------------------

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --------------------------
      # PUSH IMAGE
      # --------------------------

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/employee-profile-api

      # --------------------------
      # DEPLOY TO EC2
      # --------------------------

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/employee-profile-api

            docker stop employee-api || true
            docker rm employee-api || true

            docker run -d \
              -p 80:3000 \
              --name employee-api \
              ${{ secrets.DOCKERHUB_USERNAME }}/employee-profile-api
